id: I39383E48
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:14:46+00:00'
last_modified: '2022-06-08T10:51:21.463979+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6849
  title: ནུབ་ཁུལ་གྱི་སྐྱེས་ཁམས་ཁོར་ཡུག་སྲུང་སྐྱོབས་དང་འཛུགས་སྐྲུན་བྱེད་པའི་ཚན་རྩལ་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BD4:
      image_group_id: I3CN6851
      title: Volume 1 of nub khul gyi skyes khams khor yug srung skyobs dang 'dzugs
        skrun byed pa'i tshan rtsal shes bya'i dri ba dris lan/
      total_pages: 110
      order: 1
      base_file: 9BD4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
