id: opecha:P006991
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6849
  title: ནུབ་ཁུལ་གྱི་སྐྱེས་ཁམས་ཁོར་ཡུག་སྲུང་སྐྱོབས་དང་འཛུགས་སྐྲུན་བྱེད་པའི་ཚན་རྩལ་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  volume: ''
  author: ''
