id: P006991
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6849
  title: ནུབ་ཁུལ་གྱི་སྐྱེས་ཁམས་ཁོར་ཡུག་སྲུང་སྐྱོབས་དང་འཛུགས་སྐྲུན་བྱེད་པའི་ཚན་རྩལ་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  volumes:
    de40cf09e6e84ebab34bf5a2fc47b87c:
      image_group_id: I3CN6851
      title: ''
      volume_number: 1
      total_pages: 110
ebook_metadata:
  title: ནུབ་ཁུལ་གྱི་སྐྱེས་ཁམས་ཁོར་ཡུག་སྲུང་སྐྱོབས་དང་འཛུགས་སྐྲུན་བྱེད་པའི་ཚན་རྩལ་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  sku: P006991
  cover: cover.jpg
  layers:
  - pagination
